# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

require 'open-uri'

User.destroy_all
Song.destroy_all

demouser = User.create(email: 'demo@user.com', username: 'demouser', password: 'abcdegf')
klamar = User.create(email: 'klamarxoxo@aol.com', username: 'Kendrick Lamar', password:'asdfghj')
DUAL = User.create(email: 'asdfasasdf@aol.com', username: 'Dua Lipa', password:'asdfghj')
Taylor = User.create(email: 'Tyskhbwef', username: 'Taylor Swift', password:'asdfghj')
Green = User.create(email: 'klamaradfgawrxoxo@aol.com', username: 'Green Day', password:'asdfghj')
Miles = User.create(email: 'klamaegrqegewfgrxoxo@aol.com', username: 'Miles Davis', password:'asdfghj')
Coltrane = User.create(email: 'klamarxwefwefoxo@aolee.com', username: 'John Coltrane', password:'asdfghj')
Zeppelin = User.create(email: 'klasdfsfdmarxoxo@aol.com', username: 'Led Zeppelin', password:'asdfghj')
Jay = User.create(email: 'klamwwwwwarxoxo@aol.com', username: 'Jay-Z', password:'asdfghj')
Lizzo = User.create(email: 'klamarwewexoxo@aol.com', username: 'Lizzo', password:'asdfghj')
Rocky = User.create(email: 'klawwwefefmarxoxo@aol.com', username: 'A$AP Rocky', password:'asdfghj')
Post = User.create(email: 'wwefwefklamarxoxo@aolwefwef.com', username: 'Post Malone', password:'asdfghj')
Ariana = User.create(email: 'klamaouiwnrfrxoxo@aol.com', username: 'Ariana Grande', password:'asdfghj')
Radiohead = User.create(email: 'klamadsadsarxoxo@aasdol.com', username: 'Radiohead', password:'asdfghj')
REM = User.create(email: 'klasdadsamarxoxo@aoadsadl.com', username: 'REM', password:'asdfghj')
Halen = User.create(email: 'klamkinwerfarxoxo@aol.com', username: 'Van Halen', password:'asdfghj')


KlamarProPic = open('https://notecloud-seeds.s3.amazonaws.com/Kendrick_Lamar.jpg')
KlamarCover = open('https://notecloud-seeds.s3.amazonaws.com/Kendrick_Cover.jpg')
klamar.profile_picture.attach({io: KlamarProPic, filename: 'Kendrick_Lamar.jpg'})
klamar.cover_photo.attach({io: KlamarCover, filename: 'Kendrick_Cover.jpg'})

DUAPic = open('https://notecloud-seeds.s3.amazonaws.com/DUALIPA.jpg')
DUAL.profile_picture.attach({io: DUAPic, filename: 'DUALIPA.jpg'})
TAYpic = open('https://notecloud-seeds.s3.amazonaws.com/TSWIFT.jpg')
Taylor.profile_picture.attach({io: TAYpic, filename: 'TSWIFT.jpg'})
GREENpic = open('https://notecloud-seeds.s3.amazonaws.com/GREEN.jpg')
Green.profile_picture.attach({io: GREENpic, filename: 'GREEN.jpg'})
Milespic = open('https://notecloud-seeds.s3.amazonaws.com/MILESD.jpg')
Miles.profile_picture.attach({io:Milespic, filename: 'MILESD.jpg'})
Coltranepic = open('https://notecloud-seeds.s3.amazonaws.com/JCOLTRANE.jpg')
Coltrane.profile_picture.attach({io:Coltranepic, filename: 'JCOLTRANE.jpg'})
zeppic = open('https://notecloud-seeds.s3.amazonaws.com/LEDZEP.jpg')
Zeppelin.profile_picture.attach({io:zeppic, filename: 'LEDZEP.jpg'})
Jaypic = open('https://notecloud-seeds.s3.amazonaws.com/JAYZ.jpg')
Jay.profile_picture.attach({io:Jaypic, filename: 'JAYZ.jpg'})
Lizzopic = open('https://notecloud-seeds.s3.amazonaws.com/LIZZO.jpg')
Lizzo.profile_picture.attach({io:Lizzopic, filename:'LIZZO.jpg'})
Rockypic = open('https://notecloud-seeds.s3.amazonaws.com/ASAP.jpeg')
Rocky.profile_picture.attach({io: Rockypic, filename:'ASAP.jpeg'})
Postpic = open('https://notecloud-seeds.s3.amazonaws.com/POSTMALONE.jpg')
Post.profile_picture.attach({io: Postpic, filename:'POSTMALONE.jpg'})
Arianapic = open('https://notecloud-seeds.s3.amazonaws.com/ARIANA.jpg')
Ariana.profile_picture.attach({io:Arianapic, filename: 'ARIANA.jpg'})
Radioheadpic = open('https://notecloud-seeds.s3.amazonaws.com/RADIOHEAD.jpg')
Radiohead.profile_picture.attach({io: Radioheadpic, filename: 'RADIOHEAD.jpg'})
REMpic = open('https://notecloud-seeds.s3.amazonaws.com/REM.jpg')
REM.profile_picture.attach({io: REMpic, filename: 'REM.jpg'})
Halenpic = open('https://notecloud-seeds.s3.amazonaws.com/VAN+HALEN.jpeg')
Halen.profile_picture.attach({io: Halenpic, filename: 'VAN+HALEN.jpeg'})



demouserPro = open('https://notecloud-seeds.s3.amazonaws.com/Demo_Profile.png')
demouserCov = open('https://notecloud-seeds.s3.amazonaws.com/Demo_Cover.jpeg')

demouser.profile_picture.attach({io: demouserPro, filename: 'Demo_Profile.png', content_type: 'image/png' })
demouser.cover_photo.attach({io: demouserCov, filename: 'Kendrick_Cover.jpg'})

humble = Song.create(title: 'HUMBLE', user_id: klamar.id, genre: 'rap', hyperlink: 'HUMBLE')

humble_track = open('https://notecloud-seeds.s3.amazonaws.com/08+HUMBLE..m4a')

humble_picture = open('https://notecloud-seeds.s3.amazonaws.com/Humble.jpg')
humble.track.attach({io: humble_track, filename: '08 HUMBLE..m4a'})
humble.photo.attach({io: humble_picture, filename: 'Humble.jpg'})

Dont = Song.create(title: "Don't Start Now", user_id: demouser.id, genre: 'Pop', hyperlink: 'DontStart')
Donttrack = open("https://notecloud-seeds.s3.amazonaws.com/01+Don't+Start+Now.m4a")
Dont.track.attach({io: Donttrack, filename: "01 Don't Start Now.m4a"})
Dontpic = open('https://notecloud-seeds.s3.amazonaws.com/DUALIPA.jpg')
Dont.photo.attach({io: Dontpic, filename: 'DUALIPA.jpg'})

Lights = Song.create(title: "Lights Up", user_id: demouser.id, genre: 'Rock', hyperlink: 'LightsUp')
LightsTrack = open('https://notecloud-seeds.s3.amazonaws.com/04+Lights+Up.m4a')
Lights.track.attach({io: LightsTrack, filename: '04 Lights Up.m4a'})
Lightspic = open('https://notecloud-seeds.s3.amazonaws.com/harryS.jpeg')
Lights.photo.attach({io: Lightspic, filename: 'harryS.jpeg'})

Nikes = Song.create(title: "Nikes", user_id: klamar.id, genre: 'SadBoy', hyperlink: 'Nikes')
NikesTrack = open('https://notecloud-seeds.s3.amazonaws.com/01+Nikes.m4a')
Nikes.track.attach({io: NikesTrack, filename: '01 Nikes.m4a'})
Nikespic = open('https://notecloud-seeds.s3.amazonaws.com/FRANKOCEAN.jpeg')
Nikes.photo.attach({io: Nikespic, filename: 'FRANKOCEAN.jpeg'})

Monte = Song.create(title: "Monte Carlo", user_id: demouser.id, genre: 'Chill', hyperlink: 'MonteCarlo')
MonteTrack = open('https://notecloud-seeds.s3.amazonaws.com/09+Monte+Carlo+(feat.+Wet).m4a')
Monte.track.attach({io: MonteTrack, filename:'09 Monte Carlo (feat. Wet).m4a' })
MontePic = open('https://notecloud-seeds.s3.amazonaws.com/TORIMOI.jpg')
Monte.photo.attach({io: MontePic, filename: 'TORIMOI.jpg'})

Greatest = Song.create(title: "The Greatest", user_id: demouser.id, genre: 'Indie', hyperlink: 'Greatest')
GreatestTrack = open('https://notecloud-seeds.s3.amazonaws.com/11+The+greatest.m4a')
Greatest.track.attach({io: GreatestTrack, filename: '11 The greatest.m4a'})
Greatestpic = open('https://notecloud-seeds.s3.amazonaws.com/LANADEL.jpg')
Greatest.photo.attach({io: Greatestpic, filename: 'LANADEL.jpg'})

play1 = Playlist.create(user_id: demouser.id, title: "80's Metal")
play1pic = open('https://notecloud-seeds.s3.amazonaws.com/80METAL.jpg')
play1.photo.attach({io: play1pic, filename: '80METAL.jpg'})
play2 = Playlist.create(user_id: demouser.id, title: "Indie Rock")
play2pic = open('https://notecloud-seeds.s3.amazonaws.com/INDIEROCK.jpg')
play2.photo.attach({io: play2pic, filename: 'INDIEROCK.jpg'})
play3 = Playlist.create(user_id: demouser.id, title: "New Hip Hop")
play3pic = open('https://notecloud-seeds.s3.amazonaws.com/NEWHIPHOP.jpg')
play3.photo.attach({io: play3pic, filename: 'NEWHIPHOP.jpg'})
play4 = Playlist.create(user_id: demouser.id, title: "Fresh Pressed Tracks")
play4pic = open('https://notecloud-seeds.s3.amazonaws.com/NEWMUSIC.png')
play4.photo.attach({io: play4pic, filename: 'NEWMUSIC.png'})
play5 = Playlist.create(user_id: klamar.id, title: "Drum & Bass")
play5pic = open('https://notecloud-seeds.s3.amazonaws.com/DRUMANDBASS.jpeg')
play5.photo.attach({io: play5pic, filename: 'DRUMANDBASS.jpeg'})
play6 = Playlist.create(user_id: klamar.id, title: "Classical")
play6pic = open('https://notecloud-seeds.s3.amazonaws.com/CLASSICAL.jpeg')
play6.photo.attach({io: play6pic, filename: 'CLASSICAL.jpeg'})
play7 = Playlist.create(user_id: demouser.id, title: "Best Country Now")
play7pic = open('https://notecloud-seeds.s3.amazonaws.com/COUNTRY.gif')
play7.photo.attach({io: play7pic, filename: 'COUNTRY.gif'})
play8 = Playlist.create(user_id: demouser.id, title: "Live Electronic")
play8pic = open('https://notecloud-seeds.s3.amazonaws.com/EDM.jpg')
play8.photo.attach({io: play8pic, filename: 'EDM.jpg'})
play9 = Playlist.create(user_id: demouser.id, title: "90's Punk")
play9pic = open('https://notecloud-seeds.s3.amazonaws.com/90PUNK.jpg')
play9.photo.attach({io: play9pic, filename: '90PUNK.jpg'})
play10 = Playlist.create(user_id: klamar.id, title: "Trending")
play10pic = open('https://notecloud-seeds.s3.amazonaws.com/TRENDING.jpg')
play10.photo.attach({io: play10pic, filename: 'TRENDING.jpg'})
play11 = Playlist.create(user_id: demouser.id, title: "Hip-Hop Party Starters")
play11pic = open('https://notecloud-seeds.s3.amazonaws.com/HIPHOPPARTY.jpg')
play11.photo.attach({io: play11pic, filename:'HIPHOPPARTY.jpg'})
play12 = Playlist.create(user_id: demouser.id, title: "Chill Pop")
play12pic = open('https://notecloud-seeds.s3.amazonaws.com/CHILLPOP.jpg')
play12.photo.attach({io: play12pic, filename: 'CHILLPOP.jpg'})
play13 = Playlist.create(user_id: demouser.id, title: "Lo-Fi Beats")
play13pic = open('https://notecloud-seeds.s3.amazonaws.com/LOFI.jpeg')
play13.photo.attach({io: play13pic, filename: 'LOFI.jpeg'})
play14 = Playlist.create(user_id: demouser.id, title: "Latin")
play14pic = open('https://notecloud-seeds.s3.amazonaws.com/LATIN.jpg')
play14.photo.attach({io: play14pic, filename: 'LATIN.jpg'})
play15 = Playlist.create(user_id: demouser.id, title: "Positive Dance Vibes")
play15pic = open('https://notecloud-seeds.s3.amazonaws.com/CLUB.jpg')
play15.photo.attach({io: play15pic, filename: 'CLUB.jpg'})
play16 = Playlist.create(user_id: klamar.id, title: "R&B Workout")
play16pic = open('https://notecloud-seeds.s3.amazonaws.com/RBWORK.jpg')
play16.photo.attach({io: play16pic, filename: 'RBWORK.jpg'})

PlaylistTrack.create(track_id: humble.id, playlist_id: play16.id)
Follow.create(user_id: demouser.id, follower_id: klamar.id)